parameters:
#    zither_store.example.class: Zither\StoreBundle\Example

services:
#    zither_store.example:
#        class: %zither_store.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
